In [5]:
import numpy as np
import scipy
from scipy.stats import multivariate_normal

In [4]:
multivariate_normal.pdf(\)

AttributeError: module 'scipy' has no attribute 'stats'

In [5]:
A, B = np.genfromtxt("task2_points", usecols=range(1,9))

In [6]:
A

array([3.5 , 3.5 , 8.5 , 3.75, 8.5 , 8.75, 1.5 , 6.  ])

In [7]:
B

array([4.75, 5.  , 6.25, 5.  , 6.25, 6.  , 4.75, 6.  ])

In [32]:
pointsA = list(zip(A[::2],A[1::2]))

In [33]:
pointsA

[(1.78269, 1.41994),
 (2.39558, 1.21721),
 (2.50196, 1.92164),
 (2.09783, 2.19345)]

In [34]:
pointsB = list(zip(B[::2],B[1::2]))

In [35]:
pointsB

[(-0.500439, 0.936184),
 (2.7479, 6.90028),
 (3.39415, 2.08816),
 (6.39042, -1.08549)]

In [3]:
def step(x):
    return 1 * (x > 0)

In [4]:
def task2_hNeuron(W, X):
    bias = W[0]
    W = np.delete(W, 0, 0)
    # W.T shape == (1 x D)
    # X.T shape == (D x N)
    Y = (W.T @ X.T).T + bias
    # Y shape == (D+1 x 1)
    print(Y)
    return step(Y)

In [5]:
def sigmoid(x):
  # Our activation function: f(x) = 1 / (1 + e^(-x))
  return 1 / (1 + np.exp(-x))

In [6]:
def task2_sNeuron(W, X):
    pad = np.ones(X.shape[0])
    # X_padded shape == (D+1 x N)
    X_padded = np.vstack((pad, X.T))
    # W.T shape == (1 x D+1)
    a = (W.T @ X_padded).T
    # a shape == (D+1 x 1)
    return sigmoid(a)

In [4]:
def task2_hNN_A(X):
    # Weights for first layer
    W1 = np.asanyarray([-3.325, -0.05, 1])
    W2 = np.asanyarray([8.5, -1, 0])
    W3 = np.asanyarray([303.0/56, 11.0/28, -1])
    W4 = np.asanyarray([-7.875, 1.25, 1])

    # Outputs from first layer
    Y1 = task2_hNeuron(W1, X)
    Y2 = task2_hNeuron(W2, X)
    Y3 = task2_hNeuron(W3, X)
    Y4 = task2_hNeuron(W4, X)
    
    #  Weights for second layer
    W5 = np.array([-3.5, 1, 1, 1, 1])

    X_out = np.vstack((Y1,Y2,Y3,Y4))

    Y = task2_hNeuron(W5, X_out)

    return Y

In [15]:
X = np.asanyarray([[3.5, 3.5], [8.5,3.75],[8.5, 8.75],[1.5,6]])

In [16]:
task2_hNN_A(X)

[0.  0.  5.  2.6]
[5. 0. 0. 7.]
[3.28571429 5.         0.         0.        ]
[ 0.   6.5 11.5  0. ]
[-1.5 -1.5 -1.5 -1.5]


array([0, 0, 0, 0])