In [1]:
import numpy as np
import scipy

In [2]:
data = []
with open("data/task2_data.txt") as f:
    line = f.readline()
    line = line.split(": ")[1].rstrip()
    data.append(np.fromstring(line))

/home/apurv/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """


In [3]:
data

[array([4.27482690e-33, 4.01832057e-57, 6.23244285e-38, 1.03096611e-71,
        1.72371629e-47, 3.53541707e-57, 5.88651457e-62, 2.10898795e-52])]

In [63]:
def step(x):
    return 1 * (x > 0)

In [67]:
def task2_hNeuron(W, X):
    pad = np.ones(X.shape[0])
    # X_padded shape == (D+1 x N)
    X_padded = np.vstack((pad, X.T))
    # W.T shape == (1 x D+1)
    a = (W.T @ X_padded).T
    # a shape == (D+1 x 1)
    return step(a)

In [5]:
def sigmoid(x):
  # Our activation function: f(x) = 1 / (1 + e^(-x))
  return 1 / (1 + np.exp(-x))

In [70]:
def task2_sNeuron(W, X):
    pad = np.ones(X.shape[0])
    # X_padded shape == (D+1 x N)
    X_padded = np.vstack((pad, X.T))
    # W.T shape == (1 x D+1)
    a = (W.T @ X_padded).T
    # a shape == (D+1 x 1)
    return sigmoid(a)

In [16]:
W = np.arange(6).reshape(6,1)

In [65]:
X = np.arange(15).reshape(3,5)

In [71]:
task2_sNeuron(W, X)

[[ 40.]
 [115.]
 [190.]]


array([[1.],
       [1.],
       [1.]])

In [30]:
np.append(np.array([1,1,1]).T, X).reshape(3,6)

array([[ 1,  1,  1,  0,  1,  2],
       [ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14]])

In [39]:
X.resize((6,3))

ValueError: cannot resize this array: it does not own its data

In [43]:
np.vstack((np.array([1,1,1]), X.T))

array([[ 1,  1,  1],
       [ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
X.shape

(3, 5)

In [50]:
q = np.asanyarray([[ 40., 115., 190.]])

In [52]:
q.shape

(1, 3)

In [62]:
np.sign(-1)

-1