In [39]:
import scipy.io as sio
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [2]:
data = sio.loadmat('data/dset.mat')

In [3]:
data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'list_family', 'list_genus', 'list_species', 'X', 'Y_family', 'Y_genus', 'Y_species'])

In [31]:
Y_species = data.get('Y_species')

In [42]:
Y_species

array([[ 2],
       [ 7],
       [ 2],
       ...,
       [ 1],
       [10],
       [ 5]], dtype=int32)

In [32]:
Y_species[0]

array([2], dtype=int32)

In [40]:
X_vec = data.get('X')

In [41]:
X_vec

array([[-1.        , -0.85208478, -0.5446153 , ...,  0.03081446,
        -0.04646877, -0.10260198],
       [-1.        , -0.83122403, -0.35381633, ..., -0.05976682,
        -0.04458574,  0.01394643],
       [-1.        , -0.87307382, -0.50275353, ...,  0.08532905,
        -0.01570336, -0.07587386],
       ...,
       [-1.        , -0.52845271, -0.09051293, ...,  0.00273226,
        -0.0143477 , -0.00636827],
       [-1.        , -0.8586075 , -0.27509567, ..., -0.00910596,
        -0.00653614, -0.01747479],
       [-1.        , -0.44213437,  0.002258  , ..., -0.0188348 ,
         0.01213924,  0.01604267]])

In [54]:
X_vec[0]

array([-1.        , -0.85208478, -0.5446153 , -0.23023933, -0.15827164,
       -0.10030244, -0.11154368, -0.04217562,  0.05429012, -0.01039922,
       -0.10284336, -0.02367292,  0.00542988, -0.13799486, -0.15663055,
       -0.03263575,  0.02750404,  0.01395437, -0.01718162, -0.04397875,
       -0.0025327 ,  0.03081446, -0.04646877, -0.10260198])

In [36]:
lst_species = data.get('list_species')

In [37]:
lst_species

array([[array(['AdenomeraAndre'], dtype='<U14')],
       [array(['AdenomeraHylaedactylus'], dtype='<U22')],
       [array(['Ameeregatrivittata'], dtype='<U18')],
       [array(['HylaMinuta'], dtype='<U10')],
       [array(['HypsiboasCinerascens'], dtype='<U20')],
       [array(['HypsiboasCordobae'], dtype='<U17')],
       [array(['LeptodactylusFuscus'], dtype='<U19')],
       [array(['OsteocephalusOophagus'], dtype='<U21')],
       [array(['Rhinellagranulosa'], dtype='<U17')],
       [array(['ScinaxRuber'], dtype='<U11')]], dtype=object)

In [38]:
lst_species.size

10

In [44]:
x = np.random.random((10, 5))
y = np.random.random((10, 5))

n = x.shape[1]
cov_bias = np.mean(x * y, axis=1) - np.mean(x, axis=1) * np.mean(y, axis=1)
cov_bias * n / (n-1)

array([ 0.03230443, -0.00294949, -0.06672055,  0.03545497, -0.0232703 ,
        0.0043879 ,  0.01701321,  0.0135234 ,  0.08443097, -0.0134014 ])

In [55]:
s = np.empty((X_vec.shape[0], 1))
for i in range(X_vec.shape[0]):
    print(np.cov(X_vec[i], Y_species[i])[0][1])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [57]:
np.cov(X_vec)

array([[0.07240944, 0.06635999, 0.07043318, ..., 0.05428495, 0.06817363,
        0.05017024],
       [0.06635999, 0.06996253, 0.06796921, ..., 0.05576421, 0.06680438,
        0.05046727],
       [0.07043318, 0.06796921, 0.0737814 , ..., 0.05458264, 0.06793482,
        0.05039877],
       ...,
       [0.05428495, 0.05576421, 0.05458264, ..., 0.05087966, 0.05667166,
        0.04868696],
       [0.06817363, 0.06680438, 0.06793482, ..., 0.05667166, 0.06936868,
        0.05419381],
       [0.05017024, 0.05046727, 0.05039877, ..., 0.04868696, 0.05419381,
        0.05018458]])

In [58]:
np.unique(Y_species)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)